#! /bin/bash
#
# This script fixes up paths and URLs in a CiviCRM installation
# Typically you need this when restoring a copy of an existing installation
# The script is tuned to an installation in a docker so
# OLD_PATH and OLD_HOST need to be defined when running this script
#

if [ "$#" -ne 2 ]; then
    echo "$0 <old_path> <old_hostg>"
    exit
fi

OLD_PATH=$1
OLD_HOST=$2

db_replacement="s%mysql://[^:]*:[^@]*@[^/]*/[^?]*%mysql://joomla:joomla@localhost/joomla%"
sed -i.bak $db_replacement components/com_civicrm/civicrm.settings.php
sed -i.bak $db_replacement administrator/components/com_civicrm/civicrm.settings.php

# TODO We could figure out old path from any of the configuration files
path_replacement="s%$OLD_PATH%/var/www/html%"
sed -i $path_replacement components/com_civicrm/civicrm.settings.php
sed -i $path_replacement administrator/components/com_civicrm/civicrm.settings.php
sed -i.bak $path_replacement administrator/components/com_civicrm/civicrm/civicrm.config.php

# TODO We could figure out old host from any of the configuration files
# TODO Is there a way we could get the PORT number (when it needs to be used with localhost)
url_replacement="s%$OLD_HOST%localhost%"
sed -i $url_replacement components/com_civicrm/civicrm.settings.php
sed -i $url_replacement administrator/components/com_civicrm/civicrm.settings.php
