version: '3.3'

services:
   db:
     image: mariadb:latest
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somejoomla
       MYSQL_DATABASE: joomla
       MYSQL_USER: joomla
       MYSQL_PASSWORD: joomla

   joomla:
     depends_on:
       - db
     image: joomla-kickstart:latest
     ports:
       - "8000:80"
     restart: always
     environment:
       JOOMLA_DB_HOST: db:3306
       JOOMLA_DB_USER: joomla
       JOOMLA_DB_PASSWORD: joomla
       JOOMLA_DB_NAME: joomla
volumes:
    db_data: {}
