#! /bin/bash
#
# Rebase a CiviCRM installation by replacing relevant paths and URL:s in some settings files
#

# First argument should be an absolute path the root of the CMS installation, which is also
# assumed to be what should be replaced in the configuration files

cms_root=$1

# Second argument should be the connection string for the database: user:password@host/database
sql_connection=$2

# For Joomla
frontend=$cms_root/components/com_civicrm
backend=$cms_root/administrator/components/com_civicrm

# $civicrm_rootdir - absolute path to the root of the CiviCRM installation
# Joomla Backend & Frontend
sed -i "/^\$civicrm_root =/c\$civicrm_root = '$backend';" $backend/civicrm.settings.php
sed -i "/^\$civicrm_root =/c\$civicrm_root = '$frontend';" $frontend/civicrm.settings.php

# CIVICRM_DSN
db_connection=mysql://$sql_connection?new_link=true
sed -i "/^\s*define(\s*'CIVICRM_DSN',\s*'mysql:/cdefine('CIVICRM_DSN', '$db_connection');" $backend/civicrm.settings.php
sed -i "/^\s*define(\s*'CIVICRM_DSN',\s*'mysql:/cdefine('CIVICRM_DSN', '$db_connection');" $frontend/civicrm.settings.php


# CIVICRM_TEMPLATE_COMPILEDIR
template_compiledir=$cms_root/media/civicrm/templates_c
sed -i "/^\s*define(\s*'CIVICRM_TEMPLATE_COMPILEDIR'/c  define('CIVICRM_TEMPLATE_COMPILEDIR', '$template_compiledir');" $backend/civicrm.settings.php
sed -i "/^\s*define(\s*'CIVICRM_TEMPLATE_COMPILEDIR'/c  define('CIVICRM_TEMPLATE_COMPILEDIR', '$template_compiledir');" $frontend/civicrm.settings.php

# Replace paths in civicrm.config.php
sed -i "s:'/.*/administrator/components:'$backend/administrator/components:g" $backend/civicrm/civicrm.config.php

# To finish off, clean out any template_compile_directory
if [ -d $template_compiledir ] ; then
   echo rm -rf $template_compiledir/*
fi

echo Done
